# render.yaml
services:
  - type: web
    name: thecueroom-api
    env: node
    plan: free
    repo: https://github.com/dejayillegal/thecueroom
    branch: main
    buildCommand: cd server && npm ci && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: thecueroom-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: SMTP_HOST
        value: smtp-relay.brevo.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        fromSecret: SMTP_USER
      - key: SMTP_PASS
        fromSecret: SMTP_PASS
      - key: FROM_EMAIL
        value: support@thecueroom.xyz
    healthCheckPath: /api/health

databases:
  - name: thecueroom-db
    databaseName: thecueroom
    user: thecueroom_user
    plan: free