# render.yaml

services:
  # Backend API service
  - type: web
    name: thecueroom-api
    env: node
    repo: https://github.com/dejayillegal/thecueroom
    branch: main
    plan: free
    buildCommand: |
      NPM_CONFIG_PRODUCTION=false npm install
      npm run build:shared
      npm run build:server
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: thecueroom-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://dejayillegal.github.io
      # …add your SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, FROM_EMAIL here…

  # Frontend static site
  - type: static
    name: thecueroom-frontend
    env: node
    repo: https://github.com/dejayillegal/thecueroom
    branch: main
    plan: free
    buildCommand: |
      NPM_CONFIG_PRODUCTION=false npm ci
      npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BASE_PATH
        value: /thecueroom/
      - key: VITE_API_BASE_URL
        value: https://thecueroom-api.onrender.com
    routes:
      # proxy any /api calls back to your Render‐hosted API
      - type: rewrite
        source: /api/*
        destination: https://thecueroom-api.onrender.com/api/*
      # otherwise serve your SPA
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: thecueroom-db
    databaseName: thecueroom
    user: thecueroom_user
    plan: free
