services:
  - type: web
    name: thecueroom-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5050
      - key: DATABASE_URL
        fromDatabase:
          name: thecueroom-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: SMTP_HOST
        value: smtp-relay.brevo.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: 9108c5001@smtp-brevo.com
      - key: SMTP_PASS
        sync: false
      - key: FROM_EMAIL
        value: support@thecueroom.xyz
    healthCheckPath: /api/health

# Optional managed PostgreSQL database
# Remove this section if you use an external database
# Render will create the database and provide the connection string
# in the DATABASE_URL environment variable above

databases:
  - name: thecueroom-db
    databaseName: thecueroom
    user: thecueroom_user
    plan: free
