# render.yaml

services:
  # Backend API service
  - type: web
    name: thecueroom-api
    env: node
    plan: free
    repo: https://github.com/dejayillegal/thecueroom
    branch: main
    buildCommand: |
      NPM_CONFIG_PRODUCTION=false npm install
      npm run build:shared
      npm run build:server
    startCommand: npm run start
    # Health-check endpoint so Render won’t return 502 if your app is up
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: thecueroom-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://dejayillegal.github.io
      - key: SMTP_HOST        # ← replace with your SMTP host
        value: smtp-relay.brevo.com
      - key: SMTP_PORT        # ← replace with your SMTP port
        value: "587"
      - key: SMTP_USER        # ← replace with your SMTP username
        value: 9108c5001@smtp-brevo.com
      - key: SMTP_PASS        # ← or store in a Render Secret and reference it here
        value: your_smtp_password
      - key: FROM_EMAIL       # email address used in From: header
        value: support@thecueroom.xyz

  # Frontend static site
  - type: static
    name: thecueroom-frontend
    env: node
    plan: free
    repo: https://github.com/dejayillegal/thecueroom
    branch: main
    buildCommand: |
      NPM_CONFIG_PRODUCTION=false npm ci
      npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BASE_PATH
        value: /thecueroom/
      - key: VITE_API_BASE_URL
        value: https://thecueroom-api.onrender.com
    routes:
      # 1) Serve any matching file from dist/ first
      - type: filesystem
      # 2) Proxy all /api calls to your backend service
      - type: rewrite
        source: /api/*
        destination: https://thecueroom-api.onrender.com/api/*
      # 3) SPA fallback for all other routes
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: thecueroom-db
    databaseName: thecueroom
    user: thecueroom_user
    plan: free
