# render.yaml

services:
  # 1) Backend API
  - type: web
    name: thecueroom-api
    env: node
    plan: free
    repo: https://github.com/dejayillegal/thecueroom
    branch: main
    buildCommand: |
      # install everything (including devDeps for build & drizzle)
      NPM_CONFIG_PRODUCTION=false npm install

      # push your drizzle schema
      npm run db:push

      # seed initial data (admin user, sample posts, etc)
      npm run db:seed

      # compile the server TS → dist/server
      npm run build:server
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: thecueroom-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: SMTP_HOST
        value: smtp-relay.brevo.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        fromSecret: SMTP_USER
      - key: SMTP_PASS
        fromSecret: SMTP_PASS
      - key: FROM_EMAIL
        value: support@thecueroom.xyz
    healthCheckPath: /api/health

  # 2) Frontend Static Site
  - type: static
    name: thecueroom-frontend
    env: node
    plan: free
    repo: https://github.com/dejayillegal/thecueroom
    branch: main
    buildCommand: |
      # install & build your Vite client
      NPM_CONFIG_PRODUCTION=false npm install
      npm run build:static
    staticPublishPath: dist/client
    envVars:
      # this will be baked into your client bundle by Vite
      - key: VITE_API_BASE_URL
        value: https://thecueroom-api.onrender.com
    routes:
      # forward all /api calls back to your API service
      - type: rewrite
        source: /api/*
        destination: https://thecueroom-api.onrender.com/api/*
      # serve index.html for every other path (SPA)
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: thecueroom-db
    databaseName: thecueroom
    user: thecueroom_user
    plan: free
